test show

diff --git a/Ass1/girt-show b/Ass1/girt-show
--- a/Ass1/girt-show
+++ b/Ass1/girt-show
@@ -45,11 +45,8 @@ then
         echo "girt-show: error: '$filename' not found in index"
     fi
 else
-    if test $printing_number -gt $max_repository_number
+    if test $printing_number -le $max_repository_number
     then
-        echo "girt-show: error: unknown commit '$printing_number'"
-        exit 1
-    else
         contain=$(ls .girt/repository/$printing_number/$filename 2>/dev/null)
         if test "$contain" != ""
         then
@@ -57,5 +54,8 @@ else
         else
             echo "girt-show: error: '$filename' not found in commit $printing_number"
         fi
+    else
+        echo "girt-show: error: unknown commit '$printing_number'"
+        exit 1
     fi
 fi
