rm finished need local test

diff --git a/Ass1/girt-rm b/Ass1/girt-rm
--- a/Ass1/girt-rm
+++ b/Ass1/girt-rm
@@ -7,8 +7,8 @@ then
     :
 else
     # current .girt does not exist ----> print error
-    echo "girt-rm: error: no .girt directory containing girt repository exists"
-    exit 1
+    echo "girt-rm: error: no .girt directory containing girt repository exists";
+    exit 1;
 fi
 
 # There are 2 argvs in remove the first is force the second is cached
@@ -65,7 +65,7 @@ then
 	for file in "$filelist"
 	do
 		current_del_directory=".girt/branch/$current_branch/index/$file"
-		rm -r $current_del_directory
+		rm -r "$current_del_directory"
 	done
 fi
 # checking the flag for cached
@@ -132,8 +132,8 @@ do
 		:
 	else
 		# totally different
-		echo "girt-rm: error: '$file' in index is different to both working file and repository";
-		exit 1;
+		echo "girt-rm: error: '$file' in index is different to both working file and repository"
+		exit 1
 	fi
 done
 
@@ -147,20 +147,16 @@ then
 		for file in "$filelist"
 		do
 			current_del_directory=".girt/branch/$current_branch/index/$file"
-			rm -r $current_del_directory
+			rm -r "$current_del_directory"
 		done
 	fi
 fi
 
 # no changes of flags, check whether the index files are committed
-if [ $force_flag -ne 0 ]
+if [ $force_flag -eq 0 ]
 then
-	:
-else
-	if [ $cached_flag -ne 0 ]
+	if [ $cached_flag -eq 0 ]
 	then
-		:
-	else
 		for file in "$filelist"
 		do
 			# checking the file is exist or not
@@ -177,36 +173,37 @@ else
 							current_repo_difference=$(diff .girt/branch/$current_branch/index/$file .girt/branch/$current_branch/repository/$latest_modified_branch/$file|wc -w)
 							if [ $current_repo_difference -eq 0 ]
 							then
-								echo "girt-rm: error: '$file' in repository is different to working file";
-								exit 1;
+								echo "girt-rm: error: '$file' in repository is different to working file"
+								exit 1
+							fi
 						fi
 					fi
 				else
 					# current_dir_difference eq 0
 					if [ $change_number -eq 0 ]
 					then
-						echo "girt-rm: error: '$file' has changes staged in the index";
-						exit 1;
+						echo "girt-rm: error: '$file' has changes staged in the index"
+						exit 1
 					else
 						#if the latest repository does not have the file ,then quit
 						if [ ! -e .girt/branch/$current_branch/repository/$latest_modified_branch/$file ]
 						then
-							echo "girt-rm: error: '$file' has changes staged in the index";
-							exit 1;
+							echo "girt-rm: error: '$file' has changes staged in the index"
+							exit 1
 						else
 							#does not the same file
-							difference_repository=$(diff .girt/branch/$current_branch/index/$file .girt/branch/$current_branch/repository/$latest_modified_branch/$file|wc -w);
+							difference_repository=$(diff .girt/branch/$current_branch/index/$file .girt/branch/$current_branch/repository/$latest_modified_branch/$file|wc -w)
 							if [ $difference_repository -gt 0 ]
 							then
-								echo "girt-rm: error: '$file' has changes staged in the index";
-								exit 1;
+								echo "girt-rm: error: '$file' has changes staged in the index"
+								exit 1
 							fi
 						fi
 					fi
 				fi
 			fi
 		done
-		for file in $filelist
+		for file in "$filelist"
 		do
 			current_del_directory=".girt/branch/$current_branch/index/$file"
 			# remove
