test remove

diff --git a/Ass1/girt-rm b/Ass1/girt-rm
--- a/Ass1/girt-rm
+++ b/Ass1/girt-rm
@@ -20,6 +20,7 @@ filelist=$@
 force_option="--force"
 cached_option="--cached"
 
+
 # I just wondered that is there a situation which has force and cached at the same time
 # Notice: Whether there is a situation that
 # check the option of --force
@@ -40,7 +41,6 @@ then
 	shift
 fi
 
-#first check all files are in index
 for filename in "$filelist"
 do	
 	# file exist
@@ -86,134 +86,116 @@ then
 	exit 0;
 fi
 
-# these part of codes are similar to girt-commit
-change_counter=1
+change_counter=1;
+#then check for if the contents different between index and current dir or index and repo
 change_number=$(ls -c .girt/repository|wc -l|sed 's/ //g')
-latest_modified_branch=$(ls .girt/branch/$current_branch/repository|sort|tail -n 1)
-# checking if the content in files are different from index directory and current directory or index directory and repository
+latest_modified_branch=$(ls .girt/branch/$current_branch/repository|sort -r|head -n1)
 for file in "$filelist"
 do
-	# checking whether the file is exist or not
 	if [ -e $file ]
 	then
-		# Using the difference to check the difference
-		# Source: https://www.geeksforgeeks.org/diff-command-linux-examples/
-		current_index_difference=$(diff $file .girt/branch/$current_branch/index/$file|wc -w)
+		
+		current_index_difference=$(diff $file .girt/branch/$current_branch/index/$file|wc -w);
 		if [ $current_index_difference -gt 0 ]
 		then
-			if [ $change_number -ne 0 ]
+			if [ $change_number -eq 0 ]
 			then
-				if [ -e  .girt/branch/$current_branch/repository/$latest_modified_branch/$file ]
+				if [ $if_dcurrent_index_differenceif_curr -gt 0 ]
 				then
-					# using the word counter provided by wc
-					# Source: https://explainshell.com/explain?cmd=wc+-w
-					current_repository_difference=$(diff .girt/branch/$current_branch/index/$file .girt/branch/$current_branch/repository/$latest_modified_branch/$file|wc -w);
-					if [ $current_repository_difference -gt 0 ]
-					then
-						change_counter=0;
-					fi
-				else
 					change_counter=0;
 				fi
 			else
-				if [ $current_index_difference -gt 0 ]
+				if [ ! -e  .girt/branch/$current_branch/repository/$latest_modified_branch/$file ]
 				then
-					change_counter=0
+					change_counter=0;
 				else
-					:
+					repository_difference=$(diff .girt/branch/$current_branch/index/$file .girt/branch/$current_branch/repository/$latest_modified_branch/$file|wc -w);
+					if [ $repository_difference -gt 0 ]
+					then
+						change_counter=0;
+					fi
 				fi
 			fi
 		fi
-	else
-		:
 	fi
-	if [ $change_counter -ne 0 ]
+	if [ $change_counter -eq 0 ]
 	then
-		# has similarity
-		:
-	else
-		# totally different
-		echo "girt-rm: error: '$file' in index is different to both working file and repository"
-		exit 1
+		echo "girt-rm: error: '$file' in index is different to both to the working file and the repository";
+		exit 1;
 	fi
 done
 
-# Getting the cached flag and remove the file in the directory
-# check both cached flag and change counter 
-if [ $change_counter -eq 1 ]
+
+#only cached flag,then only rm the index file
+if [ $cached_flag -eq 1
 then
-	if [ $cached_flag -eq 1 ]
+	if [ $change_counter -eq 1 ]
 	then
-		# removed the file in the index directory
 		for file in "$filelist"
 		do
-			current_del_directory=".girt/branch/$current_branch/index/$file"
-			rm -r "$current_del_directory"
+			rm ".girt/branch/$current_branch/index/$file";
 		done
 	fi
 fi
 
-# no changes of flags, check whether the index files are committed
-if [ $force_flag -eq 0 ]
+
+#no flag at all, then need to check if the index files already be committed
+#and need to mention that if the file already be removed from the current dir,then just directly remove the index one.
+if [ $cached_flag -eq 0 ]
 then
 	if [ $cached_flag -eq 0 ]
 	then
 		for file in "$filelist"
 		do
-			# checking the file is exist or not
 			if [ -e $file ]
 			then
-				# compart the current file with the index dir
-				current_dir_difference=$(diff $file  .girt/branch/$current_branch/index/$file|wc -w)
-				if [ $current_dir_difference -ne 0 ]
+				#check the repo
+				if_dif_curr=`diff $file  .girt/branch/$current_branch/index/$file|wc -w`;
+				if [ $if_dif_curr -eq 0 ]
 				then
-					if [ $change_number -gt 0 ]
+				#if 0 repo,then quit
+					if [ $change_number -eq 0 ]
 					then
-						if [ -e .girt/branch/$current_branch/repository/$latest_modified_branch/$file ]
+						echo "girt-rm: error: '$file' has staged changes in the index";
+						exit 1;
+					else
+						#if the latest repo does not have the file ,then quit
+						if [ ! -e .girt/branch/$current_branch/repository/$latest_modified_branch/$file ]
 						then
-							current_repo_difference=$(diff .girt/branch/$current_branch/index/$file .girt/branch/$current_branch/repository/$latest_modified_branch/$file|wc -w)
-							if [ $current_repo_difference -eq 0 ]
+							echo "girt-rm: error: '$file' has staged changes in the index";
+							exit 1;
+						else
+						#does not the same file
+							if_dif_repo=`diff .girt/branch/$current_branch/index/$file .girt/branch/$current_branch/repository/$latest_modified_branch/$file|wc -w`;
+							if [ $if_dif_repo -gt 0 ]
 							then
-								echo "girt-rm: error: '$file' in repository is different to working file"
-								exit 1
+								echo "girt-rm: error: '$file' has staged changes in the index";
+								exit 1;
 							fi
 						fi
 					fi
 				else
-					# current_dir_difference eq 0
-					if [ $change_number -eq 0 ]
+					if [ $change_number -gt 0 ]
 					then
-						echo "girt-rm: error: '$file' has changes staged in the index"
-						exit 1
-					else
-						#if the latest repository does not have the file ,then quit
-						if [ ! -e .girt/branch/$current_branch/repository/$latest_modified_branch/$file ]
+						if [ -e .girt/branch/$current_branch/repository/$latest_modified_branch/$file ]
 						then
-							echo "girt-rm: error: '$file' has changes staged in the index"
-							exit 1
-						else
-							#does not the same file
-							difference_repository=$(diff .girt/branch/$current_branch/index/$file .girt/branch/$current_branch/repository/$latest_modified_branch/$file|wc -w)
-							if [ $difference_repository -gt 0 ]
+							if_dif_repo=`diff .girt/branch/$current_branch/index/$file .girt/branch/$current_branch/repository/$latest_modified_branch/$file|wc -w`;
+							if [ $if_dif_repo -eq 0 ]
 							then
-								echo "girt-rm: error: '$file' has changes staged in the index"
-								exit 1
+								echo "girt-rm: error: '$file' in the repository is different to the working file";
+								exit 1;
 							fi
 						fi
 					fi
 				fi
 			fi
 		done
-		for file in "$filelist"
-		do
-			current_del_directory=".girt/branch/$current_branch/index/$file"
-			# remove
-			rm -r "$current_del_directory"
-			# exist then delete
-			if [ -e $file ]
-			then
-				rm -r "$file"
-			fi
-		done
-	fi
+	for file in "$filelist"
+	do
+		rm ".girt/branch/$current_branch/index/$file";
+		if [ -e $file ]
+		then
+			rm "$file";
+		fi
+	done
 fi
