test branch

diff --git a/Ass1/girt-branch b/Ass1/girt-branch
--- a/Ass1/girt-branch
+++ b/Ass1/girt-branch
@@ -122,11 +122,11 @@ then
 					rm -rf $input_branch_dir
 					echo "Deleted branch '$input_branch_name'"
 				fi
+            else
+                # !!!!!!! the branch is invalid !!!!!!!!!
+                echo "girt-branch: error: invalid branch name '$input_branch_name'" >/dev/stderr
+			    exit 1
             fi
-        else
-            # !!!!!!! the branch is invalid !!!!!!!!!
-            echo "girt-branch: error: invalid branch name '$input_branch_name'" >/dev/stderr
-			exit 1
         fi
     else
         check_branch_name=$1
